[package]
name = "f4"
version = "0.2.0"
edition = "2024"
license = "MIT"
default-run = "f4"

[[bin]]
name = "f4"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
rfd = "0.15"
